name: Generate metrics

jobs:
  metrics-1:
    runs-on: ubuntu-latest

    environment: 
      name: production

    permissions:
      contents: write

    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          base: header, activity, community, repositories
          filename: metrics-1.svg
          token: ${{ secrets.METRICS_TOKEN }}

  metrics-2:
    runs-on: ubuntu-latest

    environment: 
      name: production

    permissions:
      contents: write

    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          base: ~
          filename: metrics-2.svg
          plugin_habits: yes
          plugin_habits_days: 30
          plugin_habits_from: 1000
          plugin_languages: yes
          plugin_notable: yes
          plugin_notable_from: all
          plugin_notable_indepth: yes
          plugin_notable_skipped: cesanta/mongoose
          token: ${{ secrets.METRICS_TOKEN }}

on:
  push:
    branches:
      - main

  schedule:
    - cron: 0 0 * * *

  workflow_dispatch:
